name: santifox
favicon: null
layout_spectrum: 0.96455
typography_spectrum: 0.29737
title: Santi Fox - Visual Storyteller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0089cd'
    - '#000000'
    - '#4ca0cf'
    - '#92c8e1'
    - '#323232'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
